CREATE SCHEMA NETTY_EXAMPLE_DB AUTHORIZATION DBA;
SET SCHEMA NETTY_EXAMPLE_DB;
 
DROP TABLE MEMBER IF EXISTS;

CREATE TABLE MEMBER (
	UESRID INT NOT NULL,
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL
);